### ISSUE TITLE
TODO:

### ISSUE THREAD

**Issue by xenoner1506** [kayl71/LifeSimulation#1]
Нужно сделать:
- [x] Хищники - жертвы (драки, поедания и т.д.) @kayl71 
- [x] Максимальное избавиться от "волшебных" чисел @Midyadi 
- [x] Маленькое меню во время симуляции @Midyadi 
- [x] Поле зрения (круг или сектор круга) @kayl71 

Можно сделать:
- [ ] Звуковое сопровождение (? - а надо ли) - в последнюю очередь ???

Сделано:
 - [x] Старение (параметр aging для животных, указываемый в настройках меню)
 - [x] Оптимизация обработки симуляции (лагает, когда много животных)

**Comment by xenoner1506** [comment]
__example__:
@kayl71 make hunters: 6c0f65de1040a
